version: 2
jobs:
  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: echo OLOLO

  semantic_release:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: release
          command: npm run semantic-release || true

workflows:
  version: 2
  build:
    jobs:
      - test

      - semantic_release:
          context: global
          requires:
            - test
